model:
  name: 'osnet_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['skku']
  targets: ['skku']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_erase', 'random_sized_crop']
  save_dir: 'log/osnet_x1_0_skku_softmax'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 150
  batch_size: 128
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [60]

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: True