model:
  name: 'resnet50' # 'resnet50_fc512'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501', 'cuhk03', 'prid'] # ['market1501']
  targets: ['market1501', 'cuhk03', 'prid'] # ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/resnet50_market1501-cuhk03-prid_softmax' # 'log/resnet50_market1501_softmax'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0003
  max_epoch: 100
  batch_size: 64 # 32
  fixbase_epoch: 5
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [20]

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False