model:
  name: 'plr_osnet'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501', 'cuhk03', 'cuhksysu']
  targets: ['market1501', 'cuhk03', 'sensereid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_erase'] # ['random_flip']
  save_dir: 'log/plr_osnet_triplet_market1501_cuhk03_cuhksysu-market1501_cuhk03_sensereid'

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.
    weight_x: 1.
    margin: 0. # 0.-->softmargin

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4 

train:
  optim: 'adam'
  lr: 0.000035
  max_epoch: 200
  batch_size: 64
  lr_scheduler: 'warmup'
  #multiplier: 10
  #total_epoch: 19 # torchreid/optim/lr_scheduler.py - parameters of function "build_lr_scheduler"
  stepsize: [40, 70]

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False

